# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: puma_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 200
  cycle_time_error_threshold: 0.1
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  sim_control_mode: 1  # 0: position, 1: velocity

# puma01:
# Publish all joint states ------------------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100  

# Trajectory controller -----------------------------------------------

trajectory_controller:
  type: "effort_controllers/JointTrajectoryController"

  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  constraints:
    goal_time: 0.5                   
    stopped_velocity_tolerance: 0.02

    joint_1:
      trajectory: 0.05               
      goal: 0.02         

    joint_2:
      trajectory: 0.05               
      goal: 0.02     

    joint_3:
      trajectory: 0.05               
      goal: 0.02        

    joint_4:
      trajectory: 0.05               
      goal: 0.02         

    joint_5:
      trajectory: 0.05               
      goal: 0.02         

    joint_6:
      trajectory: 0.05               
      goal: 0.02      

  gains: 

  # for computed_torque_control implementation
    # joint_1: {p: 1.0, i: 0.0, d: 2.0} 
    # joint_2: {p: 30.0, i: 0.0, d: 12.0}
    # joint_3: {p: 40.0, i: 0.0, d: 35.0}
    # joint_4: {p: 1.0, i: 0.0, d: 0.5} 
    # joint_5: {p: 1.0, i: 0.0, d: 0.5}
    # joint_6: {p: 1.0, i: 0.0, d: 0.5}

  # for simple PID
    joint_1: {p: 100.0, i: 0.0, d: 2.0} 
    joint_2: {p: 500.0, i: 0.0, d: 12.0}
    joint_3: {p: 400.0, i: 0.0, d: 35.0}
    joint_4: {p: 5.0, i: 0.0, d: 0.5} 
    joint_5: {p: 5.0, i: 0.0, d: 0.5}
    joint_6: {p: 5.0, i: 0.0, d: 0.5}

  state_publish_rate:  50            
  action_monitor_rate: 30           
  stop_trajectory_duration: 0     

# for MoveIt ----------------------------------------------------------
controller_list:
- name: posvelacc_trajectory_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6