# puma01:
generic_hw_control_loop:
  loop_hz: 250 
  cycle_time_error_threshold: 0.1 # need to set properly

hardware_interface:
  joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

posvelacc_trajectory_controller:
  type: pos_vel_acc_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  # constraints:
  #   goal_time: 0.5                   
  #   stopped_velocity_tolerance: 0.02

  #   joint_1:
  #     trajectory: 0.05               
  #     goal: 0.02         

  #   joint_2:
  #     trajectory: 0.05               
  #     goal: 0.02     

  #   joint_3:
  #     trajectory: 0.05               
  #     goal: 0.02        

  #   joint_4:
  #     trajectory: 0.05               
  #     goal: 0.02         

  #   joint_5:
  #     trajectory: 0.05               
  #     goal: 0.02         

  #   joint_6:
  #     trajectory: 0.05               
  #     goal: 0.02      

  # state_publish_rate:  25            
  # action_monitor_rate: 30           
  # stop_trajectory_duration: 0     
