force_controller:
  force_x: 
    pid: {p: 30.0, i: 0.0, d: 5.0}
  force_y: 
    pid: {p: 30.0, i: 0.0, d: 5.0}
  force_z: 
    pid: {p: 30.0, i: 0.0, d: 5.0}
  torque_x: 
    pid: {p: 30.0, i: 0.0, d: 5.0}
  torque_y: 
    pid: {p: 30.0, i: 0.0, d: 5.0}
  torque_z: 
    pid: {p: 30.0, i: 0.0, d: 5.0}
