 puma01_sim:
  # Publish all joint states ------------------------------------------
  sim_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200

  # PD controller -------------------------------

  sim_pd_plus_fw_controller:
    type: "puma01_controllers/PDplusFWController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    joint_1: 
      pid: {p: 100.0, i: 0.0, d: 2.0}
    joint_2: 
      pid: {p: 120.0, i: 0.0, d: 2.0}
    joint_3: 
      pid: {p: 110.0, i: 0.0, d: 2.0}
    joint_4: 
      pid: {p: 10.0, i: 0.0, d: 0.5}
    joint_5: 
      pid: {p: 10.0, i: 0.0, d: 0.5}
    joint_6: 
      pid: {p: 10.0, i: 0.0, d: 0.5}


  